### ISSUE TITLE
some `source=imagenet` filenames not in ILSVRC training set

### ISSUE THREAD

**Issue by lizy14** [raingo/yfcc100m-entity#2]
There are 18,500 lines with `source=imagenet` in `data/Artifacts/full.txt`, within which only 3,267 filenames can be found in ILSVRC classification/localization dataset. ILSVRC CLS-LOC training set has 1000 folders and ~1300 images per folder. 

For `data/Species-I/full.txt`, it's 1,888/13,000. 

Where can I find the rest images? are they in datasets for other tasks? which link exactly on `image-net.org` should I follow?

I'm trying to follow your work on learning from noisy label. Any help would be appreciated.

**Comment by lizy14** [comment]
I figured that a `full release` of ImageNet can definitely solve my problem, but its size `~1.2 TB` is too large for me. Could be a good idea to utilize `Image URLs` provided by ImageNet, but there are too many dead links. 

Any hints on how to gather the dataset please?

**Comment by raingo** [comment]
Please use this script to download images for the synsets:

https://bitbucket.org/raingo-ur/ner.tf/src/3b75d194d0cf8f0550547b7f76cf15760f283beb/data/label/download-imagenet.sh?at=master&fileviewer=file-view-default
